### ISSUE TITLE
Input and Output

### ISSUE THREAD

**Issue by Winnie09** [aanchalMongia/McImpute_scRNAseq#1]
Dear author,

Thanks for developing the software! I have a few questions but did not find clear answer from your paper:

1. is the input a count matrix?
2. is the output a count matrix? Has it been normalized by library size, or log2-transformed?
3. I tried to use a raw count matrix as an input, but find in output values are as large as 400+ and three quantiles are between 0 and 1?

Thanks!

**Comment by aanchalMongia** [comment]
Hey,
1. yes, the MATLAB code internally does the preprocessing  (Filtering-bad-genes-> Library size-normalization-> log transformation)
2.  As an output, you can have both the versions: 1. ) processed (Library-size normalized->log-transformed) version which is saved in `data_recovered` variable and 2. Raw count matrix which is saved in `data_recovered_raw` variable in the `run.m` script. 
3.  The possible reason  of this could be the range and scale of your single-cell data itself. I recommend that you compare the scale of the unimputed and imputed values.

Also, please re-fork the repo as I have made a minor change in the `call_mcimpute.m` function. 
Hope this helps!
