### ISSUE TITLE
Questions regardind input

### ISSUE THREAD

**Issue by davisidarta** [aanchalMongia/McImpute_scRNAseq#2]
Hi!

I'm trying to use your algorithm in my data. I'm confused about how to input the data to your algorithm - should I modify the input parameters in run.m? 

I currently have about 70k cells and 37k genes, and the data has become too large for conventional dense-matrix storage, such as .csv files. Is it possible to use a sparse matrix as an input, via a .mtx file?

**Comment by aanchalMongia** [comment]
Hey!

Yes, If you need to feed-in your own data, you will have to make changes in "run.m" script.

If you have a large sparse expression matrix, you may want to use the "mmread" function of [PROPACK ](http://sun.stanford.edu/~rmunk/PROPACK/)package in MATLAB.

Sample code:
`data=full( mmread('FileName.mtx') );`

Here are the steps to follow:
1. Download PROPACK package from [this link ](http://sun.stanford.edu/~rmunk/PROPACK/)and save it in 'data' folder in the directory of the project.
2. comment out the lines 9-17 in "run.m"
3. In place of the commented code, add the following two lines of code:

`dataname='NewDataName'`
`data=full( mmread('FileName.mtx') );`

Hope this helps !!
